server:
  port: 8088
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tyto}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: create
#      TODO change ddl-auto to validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: bookcrossing
